submit:
	@echo "Tarring Submission..."
	@touch cs357s_jg_lab.tar.gz
	@tar --exclude='jgproject' --exclude='jg_summary.txt' --exclude="Makefile" --exclude=".git" --exclude=".gitignore" --exclude="cs357s_jg_lab.tar.gz" -czf cs357s_jg_lab.tar.gz .

phony: submit
